package com.miaoshaobject.dao;

import com.miaoshaobject.dataobject.UserDo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int insert(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int insertSelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    UserDo selectByPrimaryKey(Integer id);
    UserDo selectByTelphone(String telphone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int updateByPrimaryKeySelective(UserDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int updateByPrimaryKey(UserDo record);
}