package com.miaoshaobject.dao;

import com.miaoshaobject.dataobject.UserPasswordDo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserPasswordDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int insert(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int insertSelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    UserPasswordDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int updateByPrimaryKeySelective(UserPasswordDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Thu Sep 29 20:58:07 CST 2022
     */
    int updateByPrimaryKey(UserPasswordDo record);

    UserPasswordDo selectByUserId(Integer id);
}